[package]
name = "rs-flappy"
version = "0.1.0"
edition = "2021"

[dependencies]
raylib = { version = "5.0.2" }
derive_more = { version = "1.0.0", features = ["full"] }
rand = { version = "0.9.0" }
log = { version = "0.4.5" }
env_logger = { version = "0.11.6" }
num = "0.1.43"
delegate = "0.13.2"
